@startuml

hide circle
hide members

package " Presentation Layer " as Presentation {
    class WelcomeController
    class UserController
    class OwnerController
    class PetController
    class VisitController
    class VetController
}

package " Business Logic Layer " as BusinessLogic {
    class AuthoritiesService
    class UserService
    class OwnerService
    class PetService
    class VisitService
    class VetService
}

package " Resources Layer " as Resources {
    interface AuthoritiesRepository 
    interface UserRepository 
    interface PetRepository
    interface VisitRepository
    interface OwnerRepository
}

UserController  ..> OwnerService
OwnerController ..> OwnerService
PetController ..> OwnerService
PetController ..> PetService
VisitController ..> PetService
VetController ..> VetService

AuthoritiesService ..> UserService
OwnerService ..> UserService
OwnerService ..> AuthoritiesService

OwnerService ..> OwnerRepository
UserService ..> UserRepository
AuthoritiesService ..> AuthoritiesRepository
PetService ..> PetRepository
VisitService ..> VisitRepository


@enduml
